import streamlit as st
import pandas as pd
import joblib

tipe = ['Toro Red', 'Tempranillo', 'Ribera Del Duero Red', 'Pedro Ximenez',
       'Red', 'Sherry', 'Priorat Red', 'Rioja Red', 'Rioja White',
       'Grenache', 'Cava', 'Verdejo', 'Syrah', 'Monastrell',
       'Mencia', 'Sparkling', 'Montsant Red', 'Albarino', 'Chardonnay',
       'Cabernet Sauvignon', 'Sauvignon Blanc']

region = ['Toro', 'Vino de Espana', 'Ribera del Duero', 'Montilla-Moriles',
       'Jumilla', 'Jerez-Xeres-Sherry', 'Priorato', 'Rioja', 'Bierzo',
       'Castilla y Leon', 'Campo de Borja', 'Cadiz', 'Cava',
       'Jerez Palo Cortado', 'Manzanilla', 'Valdeorras', 'Emporda',
       'Rioja Alta', 'Alicante', 'Somontano', 'Dominio de Valdepusa',
       'Ribeiro', 'Mallorca', 'Yecla', 'Cigales', 'Utiel-Requena',
       'Navarra', 'Rioja Alavesa', 'Costers del Segre', 'Sardon de Duero',
       'Malaga', 'Cataluna', 'Rueda', 'Jerez Pedro Ximenes (PX)',
       'Montsant', 'Conca de Barbera', 'Rias Baixas', 'Jerez Amontillado',
       'Tierra del Vino de Zamora', 'Penedes', 'Dehesa del Carrizal',
       'Madrid', 'Carinena', 'Condado de Huelva', 'Almansa',
       'Jerez Cream', 'Valencia', 'Sierras de Malaga', 'Ribeira Sacra',
       'El Terrerazo', 'Jerez Oloroso', 'Castilla', 'Alella',
       'Pla i Llevant', 'Pla de Bages', 'Pago Calzadilla', 'Andalucia',
       'Monterrei', 'Ribera del Gallego-Cinco Villas', 'Aragon',
       'Galicia', 'La Palma', 'Binissalem-Mallorca', 'Calatayud',
       'Arinzano', 'Tarragona', 'Extremadura', 'Murcia', 'La Mancha',
       'Otazu', 'Valdejalon', 'Mentrida', 'Terra Alta', 'Arribes',
       'Gran Canaria', 'Abona']

nama_wine = ['Tinto', 'Vina El Pison', 'Unico',
       'Unico Reserva Especial Edicion', 'El Anejon',
       'Don PX Convento Seleccion', 'Cuesta de Las Liebres', 'El Nido',
       'Toneles Moscatel', 'Pingus', 'Don PX Pedro Ximenez',
       "L'Ermita Velles Vinyes Priorat", 'Vatan Arena Tinta de Toro',
       'Ribera Del Duero Gran Reserva 12 Anos', 'Pesus Ribera del Duero',
       'Magico', 'La Faraona Bierzo (Corullon)', 'Gran Reserva 890',
       'Valbuena 5o', 'Castillo Ygay Gran Reserva Especial Blanco',
       'La Nieta', 'Malleolus de Valderramiro',
       'Malleolus de Sanchomartin', 'Alabaster', 'La Mula de la Quietud',
       'Terreus Paraje de Cueva Baja', 'Contador Rioja',
       'Maria Remirez de Ganuza', 'Cartago Paraje de Pozo',
       'Parcela El Picon Tinto', 'Termanthia', 'Clon De La Familia',
       'Aquilon Garnacha', 'Quinon de Valmira',
       '1902 Centenary Carignan Priorat', 'Tintilla de Rota',
       'Cirsion Rioja', 'Cami Pesseroles', "Turo d'en Mota", 'Priorat',
       'Reliquia Palo Cortado Sherry', 'Anada Palo Cortado 1987',
       'Daphne Glorian Red', 'El Regollar', 'Abuelo Diego Palo Cortado',
       'La Bota 78 de Oloroso', 'Touran', 'Luthier Gran Reserva',
       'Sorte O Soro Val do Bibei',
       'Reserva Particular de Recaredo Brut Nature', 'Usted',
       'Gran Reserva', 'Regina Vides Ribera del Duero', 'La Loma',
       'Recondita Armonia Monastrell Dulce',
       'Castillo Ygay Gran Reserva Especial Tinto', 'Ribera del Duero',
       'PS (Pagos Seleccionados) Ribera del Duero', 'Flor de Pingus',
       'Pago De Valtarrena', 'El Titan del Bendito', 'Dalmau Rioja',
       'Finca el Bosque', 'Pago de Santa Cruz', 'Clos Fonta Priorat',
       'Cuvee N Vinas Viejas',
       'Ribera del Duero Prestigio Pago de las Solanas',
       "Nit de Nin Mas d'en Cacador", 'VS', 'Blecua Somontano',
       'Frank Gehry Selection', 'Amaya Arzuaga (Coleccion)',
       'La Creu Alta', '5o Ano Ribera del Duero Tinto', 'Planots Priorat',
       'Capitel', 'Gran Arzuaga Ribera del Duero', 'Horcajo', 'Aurus',
       "Dolc de L'Obac", 'Trasnocho',
       'Doroteo Edicion Especial 25 Aniversario',
       'Tierra Alta de 2 Racimos Gran Reserva',
       'Reserva Especial Ribera del Duero', 'Reserva Especial',
       'Gran Buig Priorat', 'Finca Garbet',
       'Solera India Oloroso Rare Sherry', 'Amancio',
       'Gines Liebana Pedro Ximenez', 'Don PX Seleccion', 'Reserva',
       'Finca Las Naves', 'AAA', 'Vina del Olivo',
       'Les Aubaguetes Priorat',
       'Cava Enoteca Finca La Plana Brut Nature',
       'Gran Reserva Penas Aladas', 'Pena Lobera',
       'Adega do Moucho Treixadura', 'Son Negre', 'Casa Cisca Monastrell',
       'Moncerbal Bierzo (Corullon)', 'Capricho',
       'Cerrado del Castillo Rioja', 'Kalamity Rioja',
       'Conde de Aldama Amontillado', 'Respeto',
       'El Garnacho Viejo de la Familia Acha',
       'Ribera del Duero Prestigio', 'Finca Misenhora Edicion Limitada',
       'La Poza de Ballesteros', 'Reserva Rioja (Finca Ygay)', 'Idus',
       'Rosado de Larrainzar', 'Valdafoz Bierzo (Corullon)',
       'Rioja Gran Reserva', 'Valdegatiles Ribera del Duero',
       'Respublica Verdejo', 'Les Tosses',
       'Torremilanos Coleccion Ribera del Duero', 'El Carretil',
       'Taberner No. 1', 'Vina Motulleri', 'Saktih', 'Cuvee Palomar',
       'Uno Tinto', 'Macan', '1903 Centenary Grenache',
       'Galiano Seleccion Especial', 'Molino Real',
       'Etern Vinyes Molt Velles', '40 Aniversario Gran Reserva',
       'Solera BC-200',
       'Corpinnat Enoteca Reserva Particular de Recaredo', 'Toro', 'Clio',
       'Garnacha', 'Parcela El Nogal Tinto', 'Belondrade y Lurton',
       'Rioja Reserva', 'Prado Enea Gran Reserva',
       'Pedro Ximenez Tradicion 20 Years Old Vos', 'Torre Muga', 'Aro',
       'San Vicente Rioja', 'Ribera del Duero TSM',
       'Ribera Del Duero Reserva Premium 6 Anos', "Clos de L'Obac",
       'Reserva Ribera del Duero', 'Ribera Del Duero', 'Bruto',
       'Culmen Reserva Rioja', 'Vina Tondonia Gran Reserva',
       'Petit Verdot', 'Clos Martinet', 'Millenium Gran Reserva',
       'Finca Dofi', 'Gran Reserva Ribera del Duero',
       'Seleccio Especial Vinyes Velles', 'Calvario Rioja',
       'Ribera del Duero Una Cepa I', 'Grans Muralles',
       'Gran Vino Albarino', 'Cuatro Palmas Amontillado', 'Pago Garduna',
       'La Cueva del Contador Rioja', 'Solera 1830 Pedro Ximenez',
       'Que Bonito Cacareaba Blanco', 'Baron de Chirel Rioja Reserva',
       'Emeritvs (Emeritus)', 'Finca Los Hoyales Ribera del Duero',
       'Blanco', 'La Basseta', 'Territorio Luthier Reserva',
       'Vinas Viejas de Soria Ribera Del Duero',
       'Pago de Santa Cruz Gran Reserva Ribera del Duero',
       'As Sortes Val do Bibei Godello', 'Seleccion Rioja',
       'Millenium Reserva', 'Acediano', 'Gaudium', 'Pico de Luyas',
       'Grandes Anadas Rioja', 'Mas Via Gran Reserva Brut',
       'Navarra Coleccion 125 Blanco', 'Chardonnay Uno',
       'Don PX Vieja Cosecha', 'Ribas de Cabrera', 'Cenit',
       'Mas del Serral', 'Estrats', 'Fino Imperial Amontillado 30 Anos',
       'Coliseo Amontillado VORS', 'Vina Tondonia Gran Reserva Blanco',
       '8000', 'Mironia Black Edition Tempranillo', 'Miserere',
       'Alma Tobia Rioja', 'Tm', 'Doix', 'Nebro Ribera del Duero',
       'El Canto del Angel', 'Rioja Blanco Reserva',
       'Cayetano del Pino Viejisimo Palo Cortado',
       'Gratallops Partida Bellvisos', 'Coleccion Privada',
       'Finca El Canto', 'Finca Cascorrales', 'Rioja Gran Reserva 904',
       'Marques de Poley Amontillado Seleccion 1951', 'Platon Tinto',
       'Altos de Las Gateras Monastrell', 'Canta la Perdiz',
       'Marques de la Concordia VSG Premium (formerly Hacienda de Susar Rioja)',
       'Cava Kripta Gran Reserva Brut Nature',
       'Alba de Miros Rueda Verdejo', 'Pendon De La Aguilera', 'V2 Tinto',
       'Celia', 'Calmo', 'Confesor Rioja', 'La Bienquerida',
       'Seleccion Especial', 'Saca Unica', 'Palomero', 'Grano a Grano',
       'Santa Ana Pedro Ximenez 1861', 'Cuvee Julia Ribera del Duero',
       'Las Lamas Bierzo (Corullon)',
       '200 Monges Rioja Reserva Seleccion Especial', 'Galia Clos Santuy',
       'Tomas Esteban', 'Finca Las Comas Verdejo', 'Diables',
       'St Antoni de Scala Dei Priorat', 'Valdegines',
       'Seda de Oro Reserva', 'Grano a Grano Graciano - Garnacha',
       'Carraquintana de Amaren', 'Garnacha Parcela 81 Vinas Viejas',
       "Cava Enoteca Finca de L'Origen Brut Nature", 'Salinas 1237',
       'Cabernet Sauvignon', 'Finca La Colina Sauvignon Blanc',
       'Dominio del Verso Red Blend',
       'Altos R Pigeage Nacido en Barrica Blanco', 'Vinyes Altes Porrera',
       'La Vinya del Vuit (8)', 'Venus de la Figuera', 'Vendetta',
       'Ribera del Duero Reserva', 'Malleolus',
       'Seleccion Especial (Reserva)', 'Cosecha', 'Red',
       'Vina Ardanza Reserva', 'Roda I Reserva Rioja',
       '3er Ano Ribera del Duero Tinto', 'Macan Clasico',
       'Alaya Tierra (Old Vines Vieilles Vignes)', 'El Viejo',
       'Hacienda Pradolagar', '200 Monges Rioja Reserva', 'Reserva Tinto',
       'Jumilla Blue Label',
       'Palo Cortado Tradicion Vors 30 Years Sherry', 'Triga',
       'Amontillado Tradicion Vors 30 Years', 'Victorino',
       'Reserva Privada Rioja', 'Pago Negralada', 'Rejon Tempranillo',
       'Interpretacion', 'Vendimia', 'Priorat Vinyes Velles',
       'Tempranillo Reserva', 'Cream Tradicion Vos 20 Years',
       'Vatan Tinta de Toro', 'Dominio del Pidio', 'Pagos Viejos', 'An',
       'Numanthia', 'Suprema 30 Meses',
       'Whisba Tempranillo Aged 18 Months in Whisky Barrels',
       'A Mano Rioja', '200 Monges Rioja Gran Reserva',
       'La Hormiga de Antidoto', 'Le Domaine Blanco de Guarda',
       'Edicion Limitada',
       'Lealtanza Coleccion de Artistas Espanoles Sorolla',
       'Granja Gran Reserva Rioja',
       'Perez Pascuas Gran Reserva Seleccion', 'El Puntido Gran Reserva',
       'Cuvee Old Vines Unfiltered', 'Fondillon', '1730 Pedro Ximenez',
       'Cirerets', 'Vinas Viejas Verdejo', 'Tadeo Tinto',
       'Tierras de Cair Reserva', 'Gran Reserva Rosado',
       'Cava Celler Batlle', 'Rioja Blanco', 'Lapola',
       'Clos Abella Seleccion Especial', 'Pie Franco',
       'Singular V Malcorta Verdejo', 'Serral del Vell Brut Nature',
       'Seleccion Finca el Grajo Viejo',
       '30 Years VORS Pedro Ximenez Sherry', 'Malpuesto', 'Chafandin',
       'La Vina de Andres Romeo Rioja', 'Delicado Cosecha Pedro Ximenez',
       'Atlantico', 'Quincha Corral', 'Els Escurcons',
       'Vinos Singulares Tempranillo Blanco Reserva',
       'Christina Ribera del Duero', 'Desti',
       'Gran Reserva Classica Tinto', 'Godello Blanco',
       'Palo Cortado 1/10', 'Fourth Edition',
       'Seleccion de Anada Albarino Rias Baixas',
       'Albarino de Fefinanes III Ano', 'Perpetual', 'El Cel',
       'Montes Obarenes Seleccion Terroir', 'Porrera Vi de Vila',
       'Gran Ribera del Duero', 'Heretge Priorat', 'Vinas Viejas',
       'Sibarita Oloroso Jerez-Xeres-Sherry 30 Years V.O.R.S', '17',
       'Clos del Portal Tros de Clos', 'Classic', 'Minami',
       'Vi de Vila Gratallops', 'Veguin de Murua Gran Reserva',
       'O Luar do Sil Valdeorras Godello Sobre Lias', 'Teixar',
       'Anada Pedro Ximenez', 'Clos del Portal Somni', 'Les Manyes',
       'Emporda Aires de Garbet', 'Montes de Toledo Syrah',
       'Maceracion Con Pieles', 'Clos Monlleo',
       'B.Rodriguez La-Cave Quo Vadis?', 'La Solana Alta',
       'Rioja Reserva 10 Anos Despues Edicion Limitada', 'Perinet + Plus',
       'Vina de Martin Escolma Ribeiro', 'Ribera del Duero Torralvo',
       'El Cabernet F - Familiar', 'Premium', 'Hipperia Red Blend',
       'Maria Ribera del Duero', 'Vendimia Seleccionada', 'Clos Figueres',
       'Castillo de Monte la Reina Cuvee Privee', 'Amontillado Saca',
       'Queiron Reserva Vinedos Familiares', 'Don PX Gran Reserva',
       'Llanos del Almendro Ribera del Duero', 'Dolc Mataro',
       'Toro 2V Premium', 'Les Eres Vinyes Velles',
       'Gran Reserva Classica Blanco', 'The Artist',
       'Amontillado 30 Years Old V.O.R.S Sherry',
       'La Comtesse de Pazo Barrantes Albarino', '5V Blanco',
       'Finca Butaros Vinya Centenaria', 'Seleccion Privada',
       "Aponte Winemaker's Private Collection Tempranillo",
       'Cami de Cormes', '1194', 'Malabrigo Ribera del Duero',
       'Old & Plus Pedro Ximenez', 'Reserva Trajanvs', 'No. 2 Victoria',
       'Emporda Gran Claustro', 'Lalomba Finca Valhonta', 'Manyetes',
       'Pago Valdebellon', 'Guarda de Leda Seleccion Tempranillo',
       'Nun Vinya dels Taus', 'Lo Cortinelo.Lo Blanc',
       '5 Partides Gratallops Vi de La Vila',
       'Cava Ex-Vite Gran Reserva Brut', 'Summa Edicion Limitada',
       'Pago El Espino', 'Gloria Rioja', 'Petra de Valpiedra Garnacha',
       'Alto de la Caseta', 'Mas de la Rosa', 'Rioja B70', 'Don Miguel',
       'Singular Negre', 'Rioja Reserva Especial', 'Rioja Cisma',
       'Martires Rioja', 'Cava Original Brut (Espumos)',
       'Marti Reserva Penedes', 'Vina Ardanza Reserva Seleccion Especial',
       'Oloroso 30 Years Old V.O.R.S', 'Pozo Alto',
       'El Cristo de Samaniego', 'El Belisario',
       'Baron de Ona Rioja Reserva', 'Cepas Vellas Rias Baixas Albarino',
       'La Aguilera', 'Pirata', 'Hispania', 'Arousa',
       'Las Cenizas Tempranillo', 'Solanes Priorat',
       'Cava Cuvee De Prestige Trepat',
       'Felix Azpilicueta Coleccion Privada', 'Savinat Sauvignon Blanc',
       'Capricho Crianza', 'Finca La Emperatriz Vinedo Singular Tinto',
       'Galena', 'Solera PAP Palo Cortado Rare Sherry', 'Finca Helena',
       'Primordium', 'La Cuartilleja Reserva', 'Noble', 'De Garage Rioja',
       'Gran Calzadilla', '4 Varietales Coleccion Rioja', 'Oloroso',
       'Numerus Clausus',
       '200 Monges Rioja Seleccion Especial Reserva Blanco',
       '30 Years V.O.R.S Very Old Palo Cortado Blend Medium Sherry',
       'Campus Gothorum', 'La Pizca', 'La Bota 90 de Manzanilla Pasada',
       'Moradillo de Roa', 'Cofradia', 'Stairway To Heaven Rosado',
       'La Silleria', 'Planella', 'Gallaecia Rias Baixes Albarino',
       'Monada', 'Verdejo', 'Vina Garugele', 'Barrica', 'Voltons',
       'Ekam Essencia', 'Valcavado de Traslascuestas',
       'Oscar Tobia Gran Reserva Rioja', 'La Baixada', 'Seleccion',
       'Cava El Tros Nou Pinot Noir',
       'Los Dominios de Berceo Prefiloxerico', 'Old & Plus Amontillado',
       'Sao Expressiu', 'Onomastica Rioja Reserva',
       'Vina Arana Gran Reserva', 'Carinena Parcela 15 Vinas Viejas',
       'Vobiscum', 'La Navilla', 'Merlot - Syrah',
       'Casta Diva Cosecha Miel Moscatel Dulce', 'Pago de Las Costanas',
       'Cava Gran Reserva Familiar Millenium Brut',
       'Zona Zepa Monastrell', 'Alma Tobia Blanco',
       'Garnacha Vinas Centenarias',
       'El Jardin de las Iguales Vinedo Historico Garnacha',
       'Silvanus Edicion Limitada Ribera del Duero',
       'San Valentin Parellada', 'Vina Tondonia Reserva', 'PSI',
       'Ribera del Duero Crianza', 'Mas La Plana Cabernet Sauvignon',
       'Crianza Tinto', 'Bosque de Matasnos Etiqueta Blanca',
       'Matusalem Sherry VORS', 'Reserva Seleccion de la Familia',
       'Apostoles 30 Years Old Sherry', 'Gran Reserva Rioja (Finca Ygay)',
       'El Puntido',
       'Don Guido Pedro Ximenez Solera Especial Aged 20 Years',
       'Gran Reserva Rioja', 'La Baraja', 'Finca Malaveina', 'Reserva XR',
       'Alenza Ribera del Duero Gran Reserva',
       'Chardonnay Fermentado en Barrica', 'Alicante Bouschet by Tarima',
       'Oloroso Tradicion Vors 30 Years', 'Dominio de Atauta', 'Crianza',
       'Laurel', 'Seleccion La Aguilera', 'Finca Martelo',
       'Pedro Ximenez Murillo Seleccion del Centenario', 'Mirto',
       'I Gran Reserva', 'Roda Reserva Rioja', 'Rioja Vina Coqueta',
       'Vermello Vermu', 'Capellania Reserva', 'Los Tabaqueros',
       'Torre Albeniz Reserva Ribera del Duero', 'Finca El Otero',
       'Familia Comenge Reserva', 'Tierra Alta de 2 Cotas Reserva',
       'Fagus de Coto de Hayas Garnacha', 'Finca Terrerazo', 'Godello',
       'Godina Garnacha', 'QS', 'Don Miguel Comenge Reserva', '3.9',
       'Finca Iscorta Gran Reserva', 'Finca Biniagual Veran',
       'Brega Garnacha', 'Elite', 'La Mar', 'Nelin Priorat',
       'Arcos de la Frontera', 'Albarino', 'Cepas Vellas Godello',
       'Las Sabias', 'Cerro Anon Rioja Gran Reserva', 'Ekam', 'Masdeu',
       'Pantocrator', 'Senorio de Cuzcurrita Rioja',
       'Silencio de Miros Ribera Del Duero', 'Queiron Mi Lugar',
       'Purgatori Costers del Segre', 'Perfume de Sonsierra',
       'Chardonnay Roure', 'Rioja Graciano', 'ARX Arcos de la Frontera',
       'Navarra Reserva Coleccion 125', 'Venus', 'Grillo',
       'Prieto Picudo', 'Sofia', 'Finca Cuesta Clara Raro Reserva',
       'Fermentado En Barrica Blanco', 'Ribera Del Duero Gran Reserva',
       'Vinya La Scala Gran Reserva Cabernet Sauvignon',
       'Atteca Armas Garnacha Old Vines', 'Syrah (Shiraz)',
       'Campo Eliseo', 'Vinas Viejas Tempranillo', 'Vitium Reserva',
       'Lo Cabalo Reserva', 'Finca Matambres', 'Suzzane Rioja',
       'Giro de Abargues', 'Reserva Vermouth Rojo', 'Punta Esencia',
       'Pla dels Angels Rosado', 'Uro', 'Tras da Vina Albarino',
       'Masia Carreras Negre', 'Branco Vermu', 'Palmeri Navalta Garnacha',
       'La Plazuela', 'Solar de Estraunza Reserva', 'III a.C',
       'Matallana', 'Rioja Norte', 'Artigas', 'Julia',
       'Jerez-Xeres-Sherry 30 Year Old Oloroso VORS', 'Pancrudo', 'Aurea',
       'Coleccion Syrah', "Flor de Primavera Peraj Ha'abib",
       'Altos de Losada El Cepon', 'Gran Vino Blanco',
       'Crianza Vendimia Seleccionada', 'Vermouth Reserva',
       'Finca Azaya Premium', 'Ribera del Duero Tinto', 'No. 20',
       'La Casilla Amontillado', 'Palo Cortado', 'Martelo Reserva',
       'Vintage Albarino', 'Cardenal Palo Cortado VORS',
       'Vallegarcia Viognier', 'Finca la Atalaya Reserva',
       'Clos Cypres Vinyes Velles (Old Vines)', 'Castineiro Albarino',
       'Amontillado V.O.R.S', 'Altar',
       'Gran Barquero Palo Cortado Solera 25 Anos',
       'Toro Gran Elias Mora', 'Arnau Oller Seleccio de la Familia',
       'Orbus', 'Malbec', 'Altos de Losada', 'Reserva Especial Rioja',
       'La Time', 'Vendimia Tardia Moscatel', 'Hiru 3 Rioja Racimos',
       'Triaca', 'Amontillado 51-1a 30 Years VORS Sherry', 'Cyclo',
       'Maimo Garnatxa', 'Fos Baranda', 'Finca la Oracion',
       'Albarino Pedralonga', 'Mas de Masos', 'Com Tu', 'El Rocallis',
       'Iugiter', 'Ultreia Valtuille Mencia', 'La Chispa Negra',
       'Sauvignon Blanc', 'Clos Adrien', 'Laderas Rioja',
       'Blanco de Parcela', 'Finca la Beata Bobal', 'Resalte Expresion',
       'Cava Brut Milesime', 'Syrah de Matasnos',
       'Massipa de Scala Dei Garnatxa Blanca - Xenin', 'Nunci Negre',
       'Oloroso Extra Viejo 1/7', 'Musivari Gran Reserva Brut Nature',
       'Faustino de Autor Reserva Especial', 'Vinas Viejas Aguilera',
       'Juan Piernas Finca El Paso Malo Monastrell', 'Pedra de Guix',
       'Vinyes Velles de Samso', 'Malvasia', 'La Bota 69 de Amontillado',
       'Antigues Reserves', 'Baron de Chirel Verdejo Vinas Centenarias',
       'Milagros de Figuero', 'Las Botas Palo Cortado Horizontal',
       'La Riva Fino Balbaina Alta', 'Coma Bruna',
       'Palo Cortado de la Cruz de 1767', 'Grano a Grano Tempranillo',
       "S'Alou", 'Altos R Pigeage', 'Finca Monteviejo', 'Habis', '5o Ano',
       'Gaminde', 'Varietal Fermentacion Lenta',
       'El Cordero y las Virgenes',
       'Selection 1884 Vermouth Gran Reserva', 'Garnacha Tintorera',
       'Penalba Lopez Blanco', 'Cabernet', 'El Cuentista',
       'Tahulla Moscatel Blanco Seco', 'Juegabolos', 'Sketch',
       'Montsalvat', 'Sio Negre', 'Pago de Otazu Chardonnay Con Crianza',
       'Verdejo Fermentado en Barrica',
       'Vinyes Altes de Les Garrigues Vi Blanc', 'Vina Centenaria Mencia',
       'Cerro del Lobo Syrah', 'Summum Monastrell', 'Finca La Herradura',
       'Alma de Mar Albarino', 'Canasta 20 Anos Cream',
       'Rioja Anadas Frias', 'Monreal', '8 Vents Mallorca',
       "Vd'O 1 Samso - Pissarra", 'Cava Gran Reserva La Capella Brut',
       'Coleccion No. 3 Cosecha', 'Albarino Sobre Lias', 'Nobbis',
       'Rara Avis Prieto Picudo', 'Sensal', 'Campo Eliseo Blanco',
       'Blanc de Neu', 'T3rno Seleccion de 3 Parcelas Ribera del Duero',
       'Fino La Barajuela', 'Parcelas de Maturana Tinta Coleccion Rioja',
       'Reserva Real', 'Attis Embaixador Albarino', 'Vitola Reserva',
       'San Cucufate Monasterio', 'Tras Los Muros Albarino', 'CM Tinto',
       'La Loma & Los Santos Garnacha Blanca - Macabeo',
       'Gratallops Escanya-Vella', 'Lalomba Finca Ladero',
       'Oloroso En Rama', 'El Reventon Cebreros',
       'Amontillado Napoleon Vinos Viejos 30 Year Old Sherry',
       'Navarra Vendimia Tardia Coleccion 125', 'Manar dos Seixas',
       '200 Monges Edicion Exclusiva Blanco Reserva',
       'Eolic Sauvignon Blanc',
       'Finca Valmediano Tinta de Toro 16 Meses Barrica',
       'Cantos del Diablo', 'Teofilo Reyes Crianza', 'Falguera',
       'Epistem No. 3', 'Angel Ribera del Duero', 'Pleret',
       'A Torna dos Pasas Escolma Ribeiro', 'Costers Del Segre 1780',
       'Ines', 'Honoris', 'La Revelia Godello', 'Club Rioja Reserva',
       'Camino del Abuelo Vinas Viejas', 'La Morera de San Lazaro',
       'Quintanilla', 'Salvaxe', 'Vi De Glass Gewurztraminer',
       'Finca Los Quemados', 'Albarino (O Rosal)', 'Rioja',
       'Vino de Autor Ribeiro Blanco',
       'Argila Reserva 3 Anys Brut Nature', 'Octogenarius',
       'Finca La Pedrissa', 'Magister',
       'Ribera del Duero Vendimia Seleccionada VT',
       'Porcellanic VI Xarel-lo Sur Lie', 'Sibila',
       'Emporda Reserva Especial Don Miguel Mateu', '200 Cestos Godello',
       'Heaven & Hell', 'Cabrida Montsant', 'Suane Blanco', 'Pinot Noir',
       'Cerro La Isa Blanco', 'Cuvee Verdejo', 'Anadelia', 'Tabuerniga',
       'Seleccion Especial Verdejo', "Coster d'en Fornos",
       'Malvasia Volcanica', 'Laderas de Inurrieta', 'El Velado Tinto',
       'Blanco Afrutado', 'A Pita Cega', 'Naiades',
       'Fuenmayor Gran Reserva', 'Mirador de Navajas Reserva Rioja',
       'Coleccion Roberto Amillo Amontillado', '1730 Amontillado',
       'Cerro La Isa Garnacha', 'Nus del Terrer', 'Nivel', 'Le Rose',
       'Pago de las Sabinas', 'Old & Plus Oloroso',
       'Coleccion Roberto Amillo Palo Cortado', 'Gueta-Lupia',
       'Marmajuelo', 'Cava Reserva Especial Chardonnay Brut Nature',
       'Ribera del Duero Vendimia Seleccionada', 'No. 23',
       'Las Iruelas El Tiemblo', 'V Dulce de Invierno', 'Diego Magana',
       'Graciano', 'Cerro Las Cuevas Seleccion Terroir',
       'Altos R Pigeage Graciano', 'Ronda',
       'Nisia Las Suertes Verdejo Old Vines', 'Territori', 'Alomado',
       'Selma de Nin Blanco', 'Senda de Los Olivos Roble',
       'Mucho Mas Tinto', 'Coto de Imaz Rioja Gran Reserva',
       'Vina Alberdi Reserva', 'Rias Baixas Albarino Atlantico',
       '27 Ribera del Duero', 'Terras Gauda O Rosal', 'Salmos',
       'Vina Bosconia Reserva', 'Louro Godello', 'La Atalaya del Camino',
       'Rioja 150 Aniversario', 'Veraton Garnacha',
       'Alexander vs. The Ham Factory', 'Vina Alberdi Crianza',
       'Taberner Tierra de Cadiz', 'Gessami', 'Finest Old Harvest Medium',
       'Ribera del Duero Red', 'Corimbo I', 'Vermut Rojo',
       'Vina Tondonia Reserva Blanco', 'Reserva 5 Ano',
       'Del Duque Amontillado Sherry VORS',
       'Les Terrasses Velles Vinyes Priorat',
       'Les Terrasses Laderas de Pizarra', 'Inici',
       '5 Finques (Fincas) Reserva', 'Martinet Bru (Garnatxa - Syrah)',
       'Ribera Del Duero Reserva', 'Muscat',
       'Angeles de Amaren Tempranillo - Graciano', 'Bassus Pinot Noir',
       'Sericis Cepas Viejas Monastrell',
       'Rioja Reserva Fincas de Ganuza', 'Corpinnat Terrers Brut Nature',
       'Dos Cortados Palo Cortado Solera Especial Aged 20 Years',
       'Oscar Tobia Reserva Rioja', 'Rioja Satinela Blanco Semidulce',
       'Clos del Portal Negre de Negres', 'Solideo', 'Preludio',
       'Reserva Tempranillo', 'Coma Vella Priorat', 'Las Ocho (8) Tinto',
       'Pago de los Balagueses Syrah', 'Bagus Ribera del Duero',
       'Formiga de Vellut', 'Tierra Alta En 2 Maderas',
       'Propiedad  Rioja', 'Reserva Especial Icon Edition',
       'Antique Palo Cortado', 'Vina Lanciano Reserva',
       'Jalifa Amontillado Rare Old Dry Solera Especial Aged 30 Years',
       'La Felisa', 'Milmanda', 'Envidiacochina (Tete de Cuvee)', 'Adaro',
       'Fondillon Gran Reserva', 'Monastrell - Syrah Finca Espolla',
       'Santa Rosa', 'Roc Nu', 'Rias Baixas Albarino Finca Valinas',
       'Treixadura', 'Candela Cream Dulce Sweet', 'Nounat',
       'Les Brugueres']

winery_list = ['Teso La Monja', 'Artadi', 'Vega Sicilia', 'Pago de Carraovejas',
       'Toro Albala', 'Bodegas El Nido', 'Valdespino',
       'Dominio de Pingus', 'Alvaro Palacios', 'Ordonez',
       'Bodegas Valduero', 'Vina Sastre', 'Sierra Cantabria',
       'Descendientes de J. Palacios', 'La Rioja Alta',
       'Marques de Murrieta', 'Vinedos de Paganos', 'Emilio Moro',
       'Quinta de la Quietud', 'Bodegas Mauro',
       'Bodega Contador (Benjamin Romeo)', 'Remirez de Ganuza',
       'Bodegas San Roman', 'Pago de Los Capellanes', 'Bodega Numanthia',
       'Alto Moncayo', 'Mas Doix', 'Finca Moncloa', 'Bodegas Roda',
       'Martinet', 'Recaredo', 'Clos Erasmus', 'Barbadillo',
       'Gonzalez-Byass', 'Bodegas Amaren', 'Alvear', 'Equipo Navazos',
       'Morca', 'Territorio Luthier', 'Rafael Palacios', 'Terra Remota',
       'Dehesa de Los Canonigos', 'Miguel Merino', 'Gutierrez de la Vega',
       'Alion', 'Aalto', 'Carmelo Rodero', 'Dominio del Bendito',
       "Mas d'en Gil", 'Casa Castillo', 'Matarromera', 'Nin-Ortiz',
       'Vinas del Vero', 'Marques de Riscal', 'Arzuaga',
       'Bodegas Mas Alta', 'Dominio de Calogia', 'Tomas Postigo',
       'Cal Pla', 'Ossian', 'Cepa 21', 'Bodegas Vilano', 'Allende',
       'Costers del Siurana', 'Hacienda Monasterio', 'Castillo Perelada',
       'Osborne', 'Ysios', 'Marques de Grinon', 'Contino', 'Gramona',
       'Dominio del Aguila', 'Hacienda Solano', 'Francisco Garcia Perez',
       'Anima Negra', 'Castano', 'La Legua', 'Castillo de Cuzcurrita',
       'Oxer Wines', 'Bodegas Yuste',
       'Bodegas 6o Elemento - Vino Sexto Elemento',
       'Proyecto Garnachas de Espana', 'Casal de Arman', 'Vall Llach',
       'Pago de Larrainzar', 'Ukan Winery', 'Vina Real',
       'Dominio de Atauta', 'Micro Bio (MicroBio)',
       'Terroir Al Limit Soc. Lda', 'Finca Torremilanos',
       'Huerta de Albala', 'Gomez Cruzado', "Castell d'Encus",
       'Abadia Retuerta', 'Enate',
       'Benjamin de Rothschild - Vega Sicilia', 'Bodegas Aragonesas',
       'Telmo Rodriguez', 'Acustic Celler', 'Vina Pedrosa', 'Pintia',
       'Belondrade', 'Muga', 'Clos Mogador', 'Bodegas Tradicion',
       'Senorio de San Vicente', 'Francisco Barona', 'Juan Gil', 'Lan',
       'R. Lopez de Heredia', 'Adama Wines', 'Milsetentayseis',
       'Espectacle del Montsant', 'Tinto Pesquera', 'Ferrer Bobet',
       'Familia Torres', 'Pazo Barrantes', 'Tio Pepe', 'Cruz de Alba',
       'Emilio Rojo', 'Dominio de Es', 'Jesus Madrazo',
       'Bodegas Naluar & Acediano', 'Marques de Caceres', 'Trus',
       'Mestres', 'Chivite', 'Bodega Ribas', 'Vinas del Cenit',
       'Mas del Serral', 'Cervoles', 'Diez Merito', 'Marques de Burgos',
       'Penafiel', 'Tobia', 'Tresmano - Tr3smano', 'Sei Solo',
       'Finca Villacreces', 'Virgen de la Asuncion', 'Romate',
       'Sara Perez y Rene Barbier', 'Dehesa del Carrizal', 'Tarsus',
       'Beronia', 'Monte Real', 'Divina Proporcion',
       'Vina al Lado de la Casa', 'Marques de la Concordia',
       'Agusti Torello Mata', 'Dominio de Cair', 'Valquejigoso',
       'Veigamoura', 'Vizcarra', 'Legaris', 'Federico Paternina',
       'Vinicola Real', 'Losada', "Clos d'Agon", 'Sacristia AB',
       'Uvaguilera Aguilera', 'Emilio Hidalgo', 'Altos del Terral',
       'El Regajal', 'Valderiz', 'Jose Pariente', 'Amos Baneres',
       'Scala Dei', 'Bodegas Valdelana', 'Abel Mendoza Monge', 'Anayon',
       'Sierra Salinas', 'Vinos Sanz', 'Cerro San Cristobal',
       'Altos de Rioja',
       'Bodegas Celler Francisco Castillo - Clos Dominic',
       'La Vinya del Vuit', 'Venus la Universal', 'Pedralonga', 'Atalaya',
       'Matsu', 'Marques de Vargas', 'Volver', 'Tridente', 'Ausas',
       'Cillar de Silos', 'Imperial', 'Ramos-Paul', 'Bodega de Bardos',
       'Rodriguez Sanzo', 'Antidoto', 'Bosque de Matasnos', 'Altanza',
       'Remelluri', 'Perinet', 'La Vicalanda', 'Monovar', 'Alvaro Domecq',
       'Los Aguilares', 'Bodega Rento', 'Dominio do Bibei',
       'Marco Abella', 'Javier Sanz Viticultor', 'Protos', 'Harveys',
       'Orben', 'Jaro', 'Bodegas Ximenez-Spinola', 'Bodegas El Paraguas',
       'Mustiguillo', 'Vina Pomal', 'Astrales', 'Merum Priorati',
       'Hacienda Lopez de Haro', 'Cayetano del Pino', 'La Unica',
       'Pazo Senorans', 'Fefinanes', 'Resalte', 'Figuero', 'Pinea',
       'Portal del Priorat', 'Cims de Porrera', 'Casa Rojo', 'Murua',
       'Vinyes Domenech', 'Pago de Vallegarcia', 'Eulogio Pomares',
       'Sangenis I Vaque', 'Delgado Zuleta', 'VALENCISO', 'Mas Perinet',
       'Luis A. Rodriguez Vazquez', 'Chozas Carrascal',
       'Alonso del Yerro', 'Clos Figueras', 'Bodegas Monte La Reina',
       'Ontanon', 'Alta Alella', 'Bodega Elias Mora', 'Joan Simo',
       'Can Axartell', 'Juan Pinero', 'Mas Llunes', 'Bodegas Frontaura',
       'Roig Parals', 'Avgvstvs', 'Jorge Ordonez', 'Ramon Bilbao', 'Leda',
       'Enric Soler', 'Es Fangar', 'Cal Batllet - Celler Ripoll Sans',
       'Llopart', 'Portia', 'Ostatu', 'Finca Valpiedra', 'Baigorri',
       'Vivaltus', 'Comenge', 'Collbaix Celler El Moli',
       'Martinez Lacuesta', 'Pujanza', 'Albet i Noya', 'Olivier Riviere',
       'Bodegas Tierra', 'Torre de Ona',
       'Do Ferreiro (Bodegas Gerardo Mendez)', 'Martin Codax',
       'Vinedos Hermanos Hernaiz', 'Freixenet', 'Azpilicueta',
       'Veronica Salgado', 'Clos Galena',
       'Bodegas Imperiales - Abadia de San Quirce', 'Marta Mate',
       'Venta Las Vacas', 'Pago Calzadilla', 'Vivanco', 'Fernandez Gao',
       'Museum', 'Farina', 'Galindo San Millan', 'Bodegas Casa Primicia',
       'Castell Miquel', 'Barco del Corneta', "Joan d'Anguera", 'Xaloc',
       'Carlos Moro', 'Bodegas Luis Perez', 'Ladairo',
       "Conreria d'Scala Dei", 'Traslascuestas', 'Lopez Cristobal',
       'Codorniu', 'Sota els Angels', 'Berceo', 'Mas Blanch I Jove',
       'Carlos Serres', 'David Moreno', 'Edra', 'Valdelosfrailes',
       'Briego', 'Guillem Carol - Cellers Carol Valles', 'Barahonda',
       'Particular', 'Bodegas Frontonio', 'Bodegas Asenjo & Manso',
       'Luis Canas', 'Garmon', 'Williams & Humbert', 'Condado de Haza',
       'Lustau', 'Bodegas Faustino', 'St. Petroni', 'Llanos Negros',
       'Aster', 'Avancia', 'Marques de Tomares', 'Quinta Sardonia',
       'Abadal', 'Hermanos Pecina', 'Biniagual', 'Breca', 'Pradorey',
       'Terras Gauda', 'Bodega Tesalia', 'Pazo de Rubianes', 'Godeval',
       'Bodegas Olarra', 'Taron', 'Sonsierra', 'Vins Miquel Gelabert',
       'El Grillo y La Luna', 'De Moya', 'Campillo', 'Jean Leon',
       'Bodegas Ateca', 'Bodega Campo Eliseo', 'Fernandez de Pierola',
       'De Muller', 'Monteabellon', 'Pepe Mendoza Casa Agricola',
       'Vinos Guerra', 'Neo', "Terra d'Uro", 'Zarate', 'Noelia Bebelia',
       'Marti Fabra', 'Palmeri Sicilia', 'Mas Que Vinos',
       'Bodegas Estraunza', 'Pittacum', 'Bodega Sommos',
       'Celler de Capcanes', 'Arinzano', 'Pago del Vostal', 'Habla',
       'Rodriguez de Vera', 'Callejuela', 'El Maestro Sierra',
       'Paco & Lola', 'Valtravieso', 'Costers del Priorat',
       'Bodegas Urium', 'Bodega Otazu', 'Perez Barquero', 'Oller del Mas',
       'Bodegas Clunia', 'Bodegas Ochoa', "Ca l'Apotecari",
       'Josep Grau Viticultor', 'Fos', 'Hacienda Grimon', 'Capafons-Osso',
       'Can Rafols dels Caus', 'Raul Perez', 'Dominio de la Vega',
       'Juve & Camps', 'Mas de les Pereres', 'Guilera',
       "l'Infernal Combier Fischer Gerin", 'Jorge Piernas', 'Balandro',
       'M. Antonio de la Riva', 'Espelt', 'Bodegas Arfe', 'Real de Asua',
       'Vinyes dels Aspres', 'Valserrano', 'Shaya', 'Finca Rio Negro',
       'Loxera', 'Dominio Fournier', 'Bodegas Yzaguirre', 'Neton',
       'Bodega Aida i Luis', 'Cartoixa de Montsalvat',
       'El Lagar de Isilla', 'Anibal de Otero', 'Altos del Enebro',
       'Albamar', 'Can Bas', 'Atlantida', 'Atlan & Artisan', 'Olivardots',
       'Lar de Paula', 'La Val', 'Tres Piedras', 'Javi Revert',
       'Lambuena', 'Attis', 'San Cobate', 'Santa Petronila',
       'Jimenez-Landi', 'Hidalgo (La Gitana)', 'Gallina de Piel', 'Arid',
       'Bodegas Reyes', 'Hugas de Batlle', 'Bodegas Arrocal',
       'Buil & Gine', 'Castell del Remei', 'Valdubon',
       'Bodegas Y Vinedos Alilian', 'Sebio', 'Goyo Garcia Viadero',
       'Santiago Ruiz', 'Mauro Estevez', 'Mas Bertran', 'Bodegas Gama',
       'Edetaria', 'Hacienda Zorita Natural Reserve', 'Ton Rimbau',
       'Can Xanet', 'A Coroa', 'Alonso & Pedrajo', 'Mandia Vell',
       'Bodega Juan Carlos Sancha', 'Valdecuevas', 'Algueira', 'Mocen',
       'Estones', 'Bodega Tameran', 'Inurrieta', 'Flor de Chasna',
       'Lagar de Sabariz', 'Naia', 'AGE', 'Navajas', 'Vinyes del Terrer',
       'Cepas Familiares', 'Dominio de Loalva', 'Zifar',
       'Bordalas Garcia', 'Rimarts', 'Pinna Fidelis', 'Loess',
       'Dominio de Anza', 'Samsara', 'Cuentavinas', 'Felix Solis',
       'El Coto', 'Mar de Frades', 'Montecastro', 'Bodegas La Horra',
       'Baluarte', 'Hispano Suizas', 'Murviedro', 'Diez Caballero',
       'Vegalfaro', 'Palacios Remondo', 'Fernando de Castilla',
       'Bohorquez', 'Adega Familiar Eladio Pineiro', 'Culebron',
       'Enrique Mendoza', 'Clos Pons', 'Ramon do Casar', 'Binigrau']

st.set_page_config(
    page_title = "Prediksi Harga Wine",
    page_icon = "🍷"
)
model_rf = joblib.load("ML_prediksi_harga.joblib")
st.title("🍷 Prediksi Harga Wine Spain")
winery = st.selectbox("Winery", winery_list)
wine = st.selectbox("Name Wine", nama_wine)
year = st.number_input("Year Of Product", min_value=1900, max_value=2025, value=2015, step=1)
rating = st.slider("Rating",4.2, 4.9,4.2)
num_reviu = st.number_input("Num Reviews",min_value=0, max_value=32624,value=0,step=1)
negara = "Espana"
region = st.selectbox("Region", region)
type_ = st.selectbox("Type", tipe)
body = st.slider("Body", 2.0, 5.0, 2.0)
acid = st.slider("Acidity", 1.0, 3.0, 1.0)
button = st.button("Prediksi",type="primary")
if (button):
    data_baru = pd.DataFrame([{
    'winery': winery,
    'year': year,
    'wine': wine,
    'rating': rating,
    'num_reviews': num_reviu,
    'country': negara,
    'region': region,
    'type': type_,
    'body': body,
    'acidity': acid
    }])
    prediksi_harga = int(model_rf.predict(data_baru)[0] * 100)
    if (prediksi_harga <= 0):
        st.success("Sorry, the data you entered is not in our records yet.")
    else:
        if (prediksi_harga > 1000):
            prediksi_harga /= 1000
            st.success(f"Based on the data you provided, I estimate the price to be {prediksi_harga} Euro")
        else:
            st.success(f"Based on the data you provided, I estimate the price to be {prediksi_harga} Euro")